version: '3'

services:
  back:
    build: .
    ports:
      - 3000:3000
    environment:
      - PGHOST=db
      - PGUSER=postgres
    links:
      - db
    volumes:
      - .:/app
    depends_on: 
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports: 
      - 5432:5432

